version: '3.8'

services:
  node-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: tail -f /dev/null
    ports:
      - "2511:2511"
      - "6006:6006"
    volumes:
      - ../character_builder:/app
